language: go

go:
- 1.11.x
- 1.12.x
- 1.13.x


env:
- GO111MODULE=on


script:
- make go-test
- make go-build
- ls -la

deploy:
  provider: releases
  token: $GITLAB_TOKEN
  file: pohls
  cleanup: false
  on:
    tags: true