language: go

go:
- 1.13.x

git:
  depth: 1

env:
- GO111MODULE=on


jobs:
  include:
  - os: linux
    dist: trusty
    env:
    - TARGET=lnx
  - os: osx
    osx_image: xcode8.3 # Tracvis default: OS X 10.12.6 and Xcode 8.3.3
    env:
    - TARGET=mac


script:
- make go-test
- make go-build
- ls -la

deploy:
  provider: releases
  token: $GITLAB_TOKEN
  file: pohls*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true